import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

import services.EmailDomainCounter;
import services.EmailDomainCounterImpl;


public class EmailDomainsApplication {

    // Generated by https://www.randomlists.com/email-addresses
    private static final String INPUT_FILE = "src/main/java/input_email.txt";

    public static void main(String... args){
        List<String> inputList = readInputFile();
        EmailDomainCounter domainCounter = new EmailDomainCounterImpl();
        displayOutput(domainCounter.countEmailDomains(inputList));

    }

    private static void displayOutput(List<String> output) {
        for (String domain : output) {
            System.out.println(domain);
        }
    }

    private static List<String> readInputFile() {
        List<String> fileList = new ArrayList<>();
        try {
            FileReader reader = new FileReader(INPUT_FILE);
            BufferedReader bufferedReader = new BufferedReader(reader);
            String line;
            while((line = bufferedReader.readLine()) != null) {
                fileList.add(line);
            }
            return fileList;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

}
